name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/checkout@v2
    - name: installer composer
    - run: composer install
    - name: installer phpunit
    - run: composer require --dev phpunit/phpunit
    - name: Test code
    - run: composer exec phpunit/mathTest.php

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
